[package]
name = "rpsump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
anyhow = "1.0"
clippy = "0.0.302"
rppal = "0.14.1"
tokio = "1.27.0"
tokio-tungstenite = "0.18.0"
