version: '3'
services:
  web:
    image: lscr.io/linuxserver/swag:2.9.0
    container_name: swag
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - ./swag_config:/deploy/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=example.com
      - VALIDATION=http
      - SUBDOMAINS=subdomain,
      - EMAIL=email@example.com
      - ONLY_SUBDOMAINS=true
    restart: unless-stopped
