FROM ragnaroek/rust-raspberry:1.68.0

# TODO: Use non-home location
WORKDIR /usr/src/rpsump

RUN sudo dpkg --add-architecture armhf
RUN sudo apt-get update

# Install environment dependencies
RUN sudo apt-get -y install build-essential wget protobuf-compiler sqlite3 libsqlite3-dev libsqlite3-0 libc6-armhf-cross libc6-dev-armhf-cross gcc-arm-linux-gnueabihf

# Install OpenSSL 1.1.1
RUN wget https://www.openssl.org/source/openssl-1.1.1t.tar.gz
RUN tar -zxf openssl-1.1.1t.tar.gz
RUN cd openssl-1.1.1t && ./config && make test && sudo make install && sudo rm /usr/bin/openssl && sudo ln -s /usr/local/bin/openssl /usr/bin/openssl && sudo ldconfig

# Install Rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y

RUN sudo apt install -y musl-tools

ENV PATH="/home/cross/.cargo/bin:${PATH}"


COPY . .

# Install Rust target
RUN rustup target add arm-unknown-linux-gnueabihf
RUN rustup target add armv7-unknown-linux-gnueabihf

# ENV PKG_CONFIG_PATH="/usr/lib/arm-linux-gnueabihf/pkgconfig"
# ENV PKG_CONFIG_ALLOW_CROSS=true

# work
#RUN rustup target add arm-linux-gnueabihf-gcc

RUN cargo build --release --target armv7-unknown-linux-gnueabihf

ENTRYPOINT [ "/bin/bash" ]
